nameOverride: ""
fullnameOverride: ""

server:
  replicaCount: 1
  
  config:
    username: example
    password: postgres
    database: example
    idit_db_args: null
    init_db_waldir: null
    auth_method: null
  
  dataDir: /postgres/data/pgdata

  dataPersistence:
    enabled: false
    storageClassName: default
    mountPath: /postgres/data
    size: 5Gi
  
  extraEnv:
  - name: example
    value: SomeValue
  
  image:
    registry: docker.io
    repository: postgres
    tag: ""
    pullPolicy: IfNotPresent
    pullSecrets: []
  
  serviceAccount:
    create: true
    name: ""
    annotations: {}
  
  podAnnotations: {}
  
  service:
    type: ClusterIP
    port: 5432
  
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits: {}
  
  startupProbe:
    enabled: false
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: true
