Selector=nameOverride: ""
fullnameOverride: ""

replicaCount: 1

config:
  admin:
    username: admin
    password: admin
  guest:
    password: guest

image:
  repository: ghcr.io/kreditorforeningens-driftssentral-da/container-image-activemq
  pullPolicy: IfNotPresent
  tag: ""

serviceAccount:
  create: true
  name: ""
  annotations: {}
  automountServiceAccountToken: true

service:
  type: ClusterIP
  port: 5671

podAnnotations: {}

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  # limits:
  #   cpu: 250m
  #   memory: 2048Mi

persistence:
  size: 5Gi
  accessModes:
  - ReadWriteOnce
  retentionPolicy: # Beta @1.27
    whenDeleted: Retain
    whenScaled: Delete

ui:
  enabled: true
  port: 8161

gatewayApi:
  enabled: false
  httpRoute: {}
  #  parentRefs:
  #    kind: Gateway
  #    name: consul-api-gateway
  #    namespace: consul
  #  hostnames: ["localhost"]
  #  rules:
  #  - matches:
  #    - path:
  #        type: PathPrefix
  #        value: /v1/public
  #    backendRefs:
  #    - kind: Service
  #      name: payara-server
  #      port: 80

consul:
  meshEnabled: false
  intentions: []
  # - name: xxx
  #   action: allow # | deny

metrics:
  enabled: false
  image:
    repository: telegraf
    tag: alpine
    pullPolicy: IfNotPresent
  port: 9273
  path: /metrics
  serviceAnnotations:
    'prometheus.io/port': "9273"
    'prometheus.io/scrape': "true"
    'prometheus.io.scheme': http
    'prometheus.io/path': /metrics

# Example:
#
# ```yaml
# nodeSelector: |
#   beta.kubernetes.io/arch: amd64
# ```
#
# @type: string
nodeSelector: {}
