-
  op: add
  path: /spec/template/metadata/annotations/consul.hashicorp.com~1connect-service
  value: payara-server
-
  op: add
  path: /spec/template/metadata/annotations/consul.hashicorp.com~1connect-service-port
  value: '8080'
