{{- if .Values.consul.meshEnabled }}
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults

metadata:
  name: {{ printf "%s-defaults" (include "jetty.fullname" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "jetty.labels" . | nindent 4 }}

spec:
  protocol: {{ .Values.consul.serviceDefaults.protocol }}

{{- if .Values.consul.intentions }}
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions

metadata:
  name: {{ printf "%s-intentions" (include "jetty.fullname" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "jetty.labels" . | nindent 4 }}

spec:
  destination:
    name: {{ include "jetty.fullname" . }}
  sources:
  {{- range $source := .Values.consul.intentions }}
  - name: {{ $source.name }}
    action: {{ default "allow" $source.action }}
  {{- end }}
{{- end }}

{{- end }}