apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: {{ printf "%s-secrets" (include "jetty.fullname" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "jetty.labels" . | nindent 4 }}

data:
  repository_url: {{ .Values.mavenDownload.credentials.url | b64enc }}
  repository_username: {{ .Values.mavenDownload.credentials.username | b64enc }}
  repository_password: {{  .Values.mavenDownload.credentials.password | b64enc }}
