apiVersion: v1
kind: Service

metadata:
  name: {{ include "jetty.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}

spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: http
  selector:
    {{- include "jetty.selectorLabels" . | nindent 4 }}
