apiVersion: apps/v1
kind: ReplicaSet

metadata:
  name: {{ include "jetty.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "jetty.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "jetty.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jetty.selectorLabels" . | nindent 8 }}
      
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "jetty.serviceAccountName" . }}
      {{- if .Values.mavenDownload.enabled }}
      initContainers:
      - name: ansible
        image: {{ .Values.mavenDownload.image.repository }}:{{ .Values.mavenDownload.image.tag }}
        envFrom:
        - secretRef:
            name: {{ include "jetty.fullname" . }}-secrets
        env:
        - name: RESOURCE_FOLDER
          value: /maven
        - name: SCRIPT_DIR
          value: /scripts
        command: ["/scripts/ansible-entrypoint.sh"]
        #command:
        #- /bin/env
        volumeMounts:
        -
          name: maven
          mountPath: /maven
        -
          name: jetty-config
          mountPath: /scripts/ansible-entrypoint.sh
          subPath: ansible-entrypoint.sh
        -
          name: jetty-config
          mountPath: /scripts/ansible-playbook.yaml
          subPath: ansible-playbook.yaml
        -
          name: jetty-config
          mountPath: /scripts/ansible-artifacts.yaml
          subPath: ansible-artifacts.yaml
      {{- end }}
      containers:
      - name: jetty
        stdin: true
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        {{- with .Values.env }}
        env:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
          protocol: TCP
        volumeMounts:
        {{- if .Values.mavenDownload.enabled }}
        -
          name: maven
          mountPath: /maven
        {{- end }}
        -
          name: jetty-config
          mountPath: /jetty/config.yaml
          subPath: config.yaml
        {{- with .Values.command }}
        command: {{ range $_,$command := . }}
        - {{ $command }}
        {{- end }}{{ end }}
        {{- with .Values.args }}
        args: {{ range $_,$arg := . }}
        - {{ $arg }}
        {{- end }}{{ end }}
      volumes:
      - name: jetty-config
        configMap:
          name: {{ printf "%s-config" (include "jetty.fullname" .) }}
          defaultMode: 0555
          items:
          -
            key: config.yaml
            path: config.yaml
          {{- if .Values.mavenDownload.enabled }}
          -
            key: ansible-artifacts.yaml
            path: ansible-artifacts.yaml
          -
            key: ansible-playbook.yaml
            path: ansible-playbook.yaml
          -
            key: ansible-entrypoint.sh
            path: ansible-entrypoint.sh
          {{- end }}
      {{- if .Values.mavenDownload.enabled }}
      - name: jetty-secrets
        secret:
          secretName: {{ printf "%s-secrets" (include "jetty.fullname" .) }}
          optional: false
          items:
          - key: maven.env
            path: maven.env
      - name: maven
        emptyDir: {}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}