resources:
- ../../base

patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: pgadmin4
  path: patch-consul.yaml
- target:
    group: ""
    version: v1
    kind: Service
    name: pgadmin4
  path: patch-service.yaml
