apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: {{ printf "%s-secrets" (include "postgres.fullname" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "postgres.labels" . | nindent 4 }}

data:
{{- range $path,$_ := .Files.Glob "resources/secret-raw/*" }}
{{ base $path | nindent 2 }}: {{ ($.Files.Get $path) | b64enc }}
{{- end }}

{{- range $path,$_ := .Files.Glob "resources/secret-tpl/*" }}
{{ base $path | nindent 2 }}: {{ tpl ($.Files.Get $path) $ | b64enc }}
{{- end }}
