apiVersion: v1
kind: Service

metadata:
  name: {{ include "postgres.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}

spec:
  type: {{ .Values.server.service.type }}
  ports:
  - port: {{ .Values.server.service.port }}
    targetPort: tcp-postgres
    protocol: TCP
    name: tcp-postgres
  selector:
    {{- include "postgres.selectorLabels" . | nindent 4 }}
