apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: {{ include "postgres.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      {{- include "postgres.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.server.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "postgres.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.server.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "postgres.serviceAccountName" . }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.server.image.pullPolicy }}
        env:
        - name: POSTGRES_PASSWORD
          value: {{ .Values.server.config.password }}
        - name: POSTGRES_USER
          value: {{ .Values.server.config.username }}
        - name: POSTGRES_DB
          value: {{ .Values.server.config.database }}
        - name: PGDATA
          value: {{ .Values.server.dataDir }}
        envFrom:
        - secretRef:
            name: {{ include "postgres.fullname" . }}-env
        ports:
        - name: tcp-postgres
          containerPort: {{ .Values.server.service.port }}
          protocol: TCP
        resources:
          {{- toYaml .Values.server.resources | nindent 12 }}
        volumeMounts:
        - name: postgres-data
          mountPath: {{ .Values.server.dataPersistence.mountPath }}
      {{- if .Values.server.dataPersistence.enabled | not }}
      volumes:
      - name: postgres-data
        emptyDir: {}
      {{- end }}
  {{- if .Values.server.dataPersistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
      namespace: {{ .Release.Namespace | quote }}
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.server.dataPersistence.size }}
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Delete
  {{- end }}