apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: {{ printf "%s-env" (include "postgres.fullname" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "postgres.labels" . | nindent 4 }}

data:
{{- range .Values.server.env }}
  {{- .name | nindent 2 }}: {{ .value | b64enc }}
{{- end }}

{{- range .Values.server.extraEnv }}
  {{- .name | nindent 2 }}: {{ .value | b64enc }}
{{- end }}
