{{- if .Values.server.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount

metadata:
  name: {{ include "postgres.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
  {{- with .Values.server.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
