apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ printf "%s-configs" (include "postgres.fullname" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "postgres.labels" . | nindent 4 }}

data:
{{- with .Files.Glob "resources/config-raw/*" }}
{{ .AsConfig | nindent 2 }}
{{- end }}

{{- with .Files.Glob "resources/config-tpl/*" }}
{{ tpl .AsConfig $ | nindent 2 }}
{{- end }}
