apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "payara-server.fullname" . }}-config
  labels:
    {{- include "payara-server.labels" . | nindent 4 }}

data:
  preboot-commands.asadmin: |
    # Custom asadmin preboot commands
    {{- tpl .Values.server.preBootCommands . | nindent 4 | trim }}
  
  postboot-commands.asadmin: |
    # Custom asadmin postboot commands
    {{- tpl .Values.server.postBootCommands . | nindent 4 | trim }}
  
  logback.xml: |
    <!-- Custom XML -->
    {{- tpl .Values.server.logBackXml . | nindent 4 | trim }}
