apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "payara-server.fullname" . }}
  labels:
    {{- include "payara-server.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      {{- include "payara-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        'consul.hashicorp.com/connect-inject': {{ .Values.server.consul.connectInjectEnabled | quote }}
        'consul.hashicorp.com/connect-service': {{ include "payara-server.fullname" . | quote }}
        'consul.hashicorp.com/connect-service-port': {{ .Values.server.httpService.port | quote }}
        {{- with .Values.server.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "payara-server.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "payara-server.serviceAccountName" . }}
      {{- if .Values.initContainer.create }}
      initContainers:
      - name: ansible
        image: kdsda/ansible:2023.23
        envFrom:
        - secretRef:
            name: {{ include "payara-server.fullname" . }}-init-env
        env:
        - name: RESOURCE_FOLDER
          value: /maven
        - name: SCRIPT_DIR
          value: /scripts
        command: ["/bin/bash", "-c", "/scripts/init.sh"]
        volumeMounts:
        -
          name: maven
          mountPath: /maven
        -
          name: payara-init-config
          mountPath: /scripts/init.sh
          subPath: init.sh
        -
          name: payara-init-config
          mountPath: /scripts/playbook.yaml
          subPath: playbook.yaml
        -
          name: payara-init-config
          mountPath: /scripts/artifacts.yaml
          subPath: artifacts.yaml
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.server.image.pullPolicy }}
        envFrom:
        - secretRef:
            name: {{ include "payara-server.fullname" . }}-env
        env: {{- with .Values.server.env }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        ports:
        -
          name: http
          containerPort: {{ .Values.server.httpService.port }}
          protocol: TCP
        -
          name: console
          containerPort: {{ .Values.server.consoleService.port }}
          protocol: TCP
        -
          name: debug
          containerPort: {{ .Values.server.consoleService.debugPort.port }}
          protocol: TCP
        volumeMounts:
        -
          name: payara-config
          mountPath: /payara/config/logback.xml
          subPath: logback.xml
        -
          name: payara-config
          mountPath: /payara/config/preboot-commands.asadmin
          subPath: preboot-commands.asadmin
        -
          name: payara-config
          mountPath: /payara/config/postboot-commands.asadmin
          subPath: postboot-commands.asadmin
        -
          name: maven
          mountPath: /maven
        startupProbe:
          tcpSocket:
            port: {{ .Values.server.httpService.port }}
          failureThreshold: 30
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: {{ .Values.server.httpService.port }}
          failureThreshold: 3
          periodSeconds: 15
        #readinessProbe:
        #  httpGet:
        #    path: /
        #    port: http
        resources:
          {{- toYaml .Values.server.resources | nindent 10 }}
      volumes:
      - name: payara-config
        configMap:
          name: {{ include "payara-server.fullname" . }}-config
          defaultMode: 0777
          items:
          - key: logback.xml
            path: logback.xml
          - key: preboot-commands.asadmin
            path: preboot-commands.asadmin
          - key: postboot-commands.asadmin
            path: postboot-commands.asadmin
      - name: payara-init-config
        configMap:
          name: {{ include "payara-server.fullname" . }}-init-config
          defaultMode: 0777
          items:
          - key: init.sh
            path: init.sh
          - key: playbook.yaml
            path: playbook.yaml
          - key: artifacts.yaml
            path: artifacts.yaml
      - name: maven
        emptyDir: {}
      #terminationGracePeriodSeconds: 10