apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: {{ printf "%s-secrets" (include "payara-server.fullname" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "payara-server.labels" . | nindent 4 }}

data:
{{- range $path,$_ := .Files.Glob "secrets/tpl/*" }}
{{ base $path | nindent 2 }}: {{ tpl ($.Files.Get $path) $ | b64enc }}
{{- end }}

{{- range $path,$_ := .Files.Glob "secrets/*" }}
{{ base $path | nindent 2 }}: {{ tpl ($.Files.Get $path) $ | b64enc }}
{{- end }}
