{{- if .Values.server.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount

metadata:
  name: {{ include "payara-server.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "payara-server.labels" . | nindent 4 }}
{{- end }}
