{{- if .Values.initContainer.create }}
apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: {{ include "payara-server.fullname" . }}-init-env
  labels:
    {{- include "payara-server.labels" . | nindent 4 }}

data:
  repository_url: {{ .Values.initContainer.mavenCredentials.url | b64enc }}
  repository_username: {{ .Values.initContainer.mavenCredentials.username | b64enc }}
  repository_password: {{ .Values.initContainer.mavenCredentials.password | b64enc }}
{{- end }}