name: Release ActiveMQ Chart

on:
  workflow_dispatch:

  push:
    tags:
    - 'activemq-v*.*.*'
    #branches:
    #- main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    -
      name: Run 'Checkout' action
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
    -
      name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
    -
      name: Install Helm
      uses: azure/setup-helm@v3
    -
      name: Run 'Chart Releaser' action
      uses: helm/chart-releaser-action@v1.5.0
      with:
        charts_dir: /kubernetes/charts
        #config: /kubernetes/charts/cr.yaml
        skip_existing: true
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
