{{- if .Values.gatewayApi.enabled }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute

metadata:
  name: payara-internal
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "activemq.labels" . | nindent 4 }}

spec:
  {{- with .Values.gatewayApi.httpRoute }}
  {{- toYaml . | nindent 2}}
  {{- end }}
{{- end }}