{{- if .Values.gatewayApi.enabled }}
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: ReferenceGrant

metadata:
  name: gateway-reference-grant
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "activemq.labels" . | nindent 4 }}

spec:
  from:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    {{- if hasKey .Values.gatewayApi.httpRoute "parentRefs" }}
    namespace: {{ default .Release.Namespace .Values.gatewayApi.httpRoute.parentRefs.namespace }}
    {{- end }}
  to:
  - group: ""
    kind: Service
{{- end }}