apiVersion: v1
kind: Service

metadata:
  name: {{ include "activemq.fullname" . }}
  labels:
    {{- include "activemq.labels" . | nindent 4 }}

spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: auto
    protocol: TCP
    name: auto
  selector:
    {{- include "activemq.selectorLabels" . | nindent 4 }}
