nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  repository: azul/zulu-openjdk-debian
  pullPolicy: IfNotPresent
  tag: ""

nodeSelector: {}

resources:
  requests:
    cpu: 100m
    memory: 128Mi
    limits: {}

env:
- name: JVM_OPTIONS
  value: |-
    -XX:+UnlockDiagnosticVMOptions
    -XX:+PrintContainerInfo
    -XX:MaxRAMPercentage=85
    -XX:ActiveProcessorCount=1

command: ["java"]

args: ["-version"]
#- jar
#- /maven/example.jar
#- server
#- /jetty/config.yml

config: |-
  # Filename: /jetty/config.yaml

serviceAccount:
  create: true
  name: ""
  automountServiceAccountToken: true
  annotations: {}

service:
  type: ClusterIP
  port: 80

podAnnotations: {}

mavenDownload:
  enabled: false
  image:
    repository: kdsda/ansible
    tag: '2023.23'
    pullPolicy: IfNotPresent
  credentials:
    url: "example.maven.org"
    username: "anonymous"
    password: "anonymous"
  artifacts: []
  # - name: <required>
  #   repository: <required>
  #   group: <required>
  #   extension: <war>
  #   version: <latest>

gatewayApi:
  enabled: false

consul:
  meshEnabled: false
  intentions: []
  serviceDefaults:
    protocol: http
